- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
      keypair: ****
      instance_type: "t2.medium"
      image: "ami-07567b572a8b16045"
      region: "us-east-1"
      wait: yes
      group: "*****"
      count: 1
      monitoring: no
      vpc_subnet_id: "***************"
      assign_public_ip: yes
      aws_access_key: ****************
      aws_secret_key: **********************